swagger: "2.0"
info:
  description: "API for cjordanball.info website"
  version: "0.0.1"
  title: "cjbinfo-api"
host: localhost:8080
basePath: /
schemes:
  - "http"
  - "https"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  JWTAuth:
    type: apiKey
    in: header
    name: authorization
paths:
  /:
    get:
      x-swagger-router-controller: "test_controller"
      description: "A test endpoint to see if it works"
      operationId: "tester"
      parameters: []
      responses:
        200:
          description: "a simple message"
          schema:
            $ref: "#/definitions/greeting"
        401:
          $ref: "#/responses/Unauthorized"
  /bytebites/{level}:
    get:
      x-swagger-router-controller: "bytebites_controller"
      description: "A protected get route"
      operationId: 'getAllProblems'
      parameters:
        - in: path
          name: level
          required: true
          type: string
          enum:
            - easy
            - medium
            - hard
      responses:
        200:
          description: "a list of all problems by number and title"
          schema:
            $ref: "#/definitions/problemList"
        401:
          $ref: "#/responses/Unauthorized"
  /sudoku:
    post:
      x-swagger-router-controller: sudoku_controller
      description: Path to controller which will solve sudoku puzzle
      operationId: getSudokuSolution
      parameters:
        - in: body
          name: inputString
          required: true
          schema:
            type: object
            required:
              - numList
            properties:
              numList:
                type: array
                minItems: 81
                maxItems: 81
                items:
                  type: string
                  enum:
                    - "1"
                    - "2"
                    - "3"
                    - "4"
                    - "5"
                    - "6"
                    - "7"
                    - "8"
                    - "9"
                    - ""
      responses:
        200:
          description: "the sudoku solution as an array of numbers"
          schema:
            $ref: "#/definitions/sudokuSolution"
        401:
          $ref: "#/responses/Unauthorized"
responses:
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"
definitions:
  greeting:
    type: "object"
    properties:
      hi:
        type: string
        description: "a simple test string"
  problemList:
    type: array
    items:
      type: object
      properties:
        serialNumber:
          type: number
        name:
          type: string
        description:
          type: string
        methods:
          type: array
          items:
            type: string
        concepts:
          type: array
          items:
            type: string
  sudokuSolution:
    type: array
    maxItems: 81
    minItems: 81
    items:
      type: string
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
