swagger: "2.0"
info:
  description: "API for cjordanball.info website"
  version: "0.0.1"
  title: "cjbinfo-api"
host: localhost:8080
basePath: /
schemes:
  - "http"
  - "https"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  JWTAuth:
    type: apiKey
    in: header
    name: authorization
paths:
  /:
    get:
      x-swagger-router-controller: "test_controller"
      description: "A test endpoint to see if it works"
      operationId: "tester"
      parameters: []
      responses:
        200:
          description: "a simple message"
          schema:
            $ref: "#/definitions/greeting"
        401:
          $ref: "#/responses/Unauthorized"
  /goodstuff:
    get:
      x-swagger-router-controller: "test_controller"
      description: "A protected get route"
      operationId: 'testAuth'
      parameters: []
      security:
        - JWTAuth: []
      responses:
        200:
          description: "a simple message"
          schema:
            $ref: "#/definitions/greeting"
        401:
          $ref: "#/responses/Unauthorized"
responses:
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/Error"
definitions:
  greeting:
    type: "object"
    properties:
      hi:
        type: string
        description: "a simple test string"
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
